### ISSUE TITLE
Tests timing out on OpenJDK8 on s390x (which has ZeroVM)

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-systemtest#10]
Currently disabled from executing as it causes complete failures:

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_stf_systemtests/arch=s390x,os=sles12/

```
+ java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2017_07_27_16_17-b00)
OpenJDK 64-Bit Zero VM (build 25.71-b00, interpreted mode)
```

**Comment by lumpfish** [comment]
There are two ways in which the load tests might time out:
1. The java process (stf.load) attaching methods to threads monitors the threads for methods starting and ending.  If no methods end for 15 minutes, stf.load assumes the process is hung and aborts the test.
2. The stf process management layer which starts processes (for a load test that would be the java process running stf.load) receives a parameter defined in the stf automation (e.g. ClassLoadingLoadTest.java) for the maximum expected run time for the process.  If that time is exceeded, the process management layer kills the process.
Increasing the value of either value is trivial.
To increase the value of 1., we'd have to change the stf.load code.
To increase the value of 2. we'd have to change the code in the stf automation.
The downside to increasing the values is that if the process really does hang (rather than just run slowly), we will have to wait that long before the hang is detected.  It is preferable to spot a hang within 5 minutes than, say, an hour.

Perhaps we would be better not attempting to run the load tests (which mostly find dynamic compiler (JIT / Hotspot) defects) on this platform, rather than setting timeouts to what should be unnecessarily high values.
Increasing the

**Comment by sxa555** [comment]
That was the conclusion I came to as well, so I've already deactivated the execution on s390x on the openjdk8 jobs for now, but if anyone thinks of a better option we could use then we can try it :-)

**Comment by Mesbah-Alam** [comment]
Closing this issue as STF load tests are running fine on jdk11 hotspot builds on s390, e.g.  MathLoadTest here:  https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_s390x_linux/172/tapResults/

Please reopen the issue if the issue happens again.
