### ISSUE TITLE
Have a single top.xml file for systemtests 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#132]
Why do we have 3 top.xml files? 

https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/include/top.xml
https://github.com/eclipse/openj9-systemtest/blob/master/openj9.build/include/top.xml
https://github.com/AdoptOpenJDK/stf/blob/master/stf.build/include/top.xml

They are very similar. It is difficult to maintain three top.xml files. It'd be ideal if we had only one.

**Comment by lumpfish** [comment]
openj9-systemtest depends on openjdk-systemtest, openjdk-systemtest depends on stf.

stf does not depend on openjdk-systemtest, openjdk-systemtest does not depend on openj9-systemtest.  If there were only one top.xml where would you put it such that stf could be built on its own, and openjdk-systemtest could be built for testing openjdk-hotspot?

stf can be checked out and built in its own right - any project could use it in the same way openjdk-systemtest uses it.

openjdk-systemtest contains tests which can run against openjdk-hotspot or openjdk-openj9 builds.

**Comment by Mesbah-Alam** [comment]
Since STF can build on its own, while openjdk-systemtest and openj9-systemtest can't build without STF, can we have the single, consolidated top.xml in STF?

**Comment by lumpfish** [comment]
openjdk-systemtest and openj9-systemtest have some prereqs which are not required by stf:

asm
tools.jar (for compiling against jdk8)
MS Visual Studio (for compiling native test cases, stf has no native code)

The options appear to be:
1. Add everything to stf's top.xml anyway (personally I don't like the idea of making things which aren't actually prereqs prereqs).
2.
a.  Change the openjdk-systemtest build.xml to include stf's top.xml and change openjdk-systemtest's top.xml to only do the extra setup which is required for the openjdk-systemtest tests but not for stf.
b. Change the openj9-systemtest build.xml to include openjdk-systemtest's top.xml.  Since there are no additional prereqs required for openj9-systemtest vs. openjdk-systemtest no top.xml would be required in openj9-systemtest.

My preference is for option 2. @Mesbah-Alam ?

**Comment by Mesbah-Alam** [comment]
If we choose option 1 - then we end up with a single top.xml file - personally I like the idea of that. 

I guess the question here is - how often are we going to need to build STF on its own? Even though it is totally possible and useful to know that we have the option to use STF to write tests in future which are not part of openjdk-systemtest or openj9-systemtest, in reality we are not doing this too often at the moment. Whereas we are maintaining + writing STF based tests that are part of openjdk-systemtest and openj9-systemtest on a regular basis. So, in effect, we'd mostly be building STF together with openjdk-systemtest and openj9-systemtest-- in which case, fetching the full set of system test prereqs as part of STF is not a concern -- and on the plus side, we get a single top.xml. 

* 

I am also thinking of another approach : 
Can we have a flag based on which STF top.xml builds the full set of prereqs, or only the prereqs specific to STF? We could set that flag in openjdk-systemtest build.xml.

**Comment by lumpfish** [comment]
I can't see the point of having a flag in stf to say 'get prereqs for some other project'.  I'll put everything into the stf top.xml locally and see how it looks.

**Comment by lumpfish** [comment]
PRs submitted:
https://github.com/AdoptOpenJDK/stf/pull/63
https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/255
https://github.com/eclipse/openj9-systemtest/pull/89

All three PRs need to be merged at the same time.

Summary of changes:

1. Moved the prereq setup (configuration) targets for all three repositories ( AdoptOpenJDK/stf, AdoptOpenJDK/openjdk-systemtest and eclipse/openj9-systemtest to AdoptOpenJDK/stf/stf.build/include/top.xml).
2. Updated the stf make configure target to download ant 1.10.2 rather than 1.10.1.
3. Change all includes for openjdk-systemtest/openjdk.build/include/top.xml and openjdk-systemtest/openjdk.build/include/top.xml to include stf/stf.build/include/top.xml instead.
4. Consolidated the java8_xxx properties and java9_xxx properties into a single set of java_xxx properties and reduced the amount of output being echoed by the setup-java-properties macro.
- This removes the confusion caused by the naming of the java8_xxx and java9_xxx properties (but removes the option to compile different test cases with different compiler versions).
5. Removed the option to set JAVA8_HOME and JAVA9_HOME via openjdk-systemtest/openjdk.build/makefile or openj9-systemtest/openj9.build/makefile (JAVA_HOME is passed to the build as -Djava_home=xxxx)
6. Changed the calls to subant tasks to use inheritAll="true" rather than inheritAll="false". 
- This enables the use of properties to prevent repeated runs of setup targets, such as repeatedly determining the java version being used for the build
- This required all test specific properties to be renamed to have unique names
-- For example srcdir in openjdk.test.jlm/build.xml was renamed openjdk_test_jlm_srcdir
7. Fixed the native ('C') test case builds for openjdk.modularity and openj9.sharedclasses.jvmti so that they should now build on all platforms.
8. The changes also mean that the output from the build overall is much reduced and the build runs much faster.

**Comment by lumpfish** [comment]
@Mesbah-Alam - are we now OK to close this issue and the related ones?

**Comment by Mesbah-Alam** [comment]
Yes, system tests are running fine (e.g. there are some failures which are unrelated to this0 after related PRs were merged. So, we can close these 3 issues at this point. Thanks @lumpfish

**Comment by Mesbah-Alam** [comment]
All PRs related to this issue has been merged and are working. Closing this Issue at this point. Thanks @lumpfish
