### ISSUE TITLE
system test material build failure on Mac OS X jdk8 hotspot 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-systemtest#225]
Single occurence of failure seen on Feb 13, on test-macincloud-macos1010-1
[openjdk8_hs_systemtest_x86-64_macos](https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_x86-64_macos/245/console) failed to build: 

05:40:57 /Users/jenkins/workspace/openjdk8_hs_systemtest_x86-64_macos/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:555: java os.name property value ${java9.os.name} not recognised.  Update the get-platform-prefix macrodef in openjdk.build/include/top.xml

**Comment by smlambert** [comment]
Happened again, https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_j9_systemtest_x86-64_macos/107/console

@lumpfish - any ideas why sometimes the platform prefix would get populated and sometimes not?

**Comment by lumpfish** [comment]
Unless overrides have been specified, the build should be building with the java running ant.  So that may be the java specified by ANT_HOME, or JAVA_HOME, or possibly the path.  We have seen situations where there is a JRE being used rather than a JDK, when javac cannot be found, or one from a different version is found via the path.

**Comment by smlambert** [comment]
This is not a consistent failure as far as I can tell, which perhaps makes it even strange-r...  perhaps there was some machine churn with a JRE set as boot sdk or some such thing on the 2 reported occasions.  I have not seen this in a while, so will close for now.   We can always re-open if it shows up again.
