### ISSUE TITLE
JCK tests fail quickly with: Nothing to be done for 'test.jck8b.noconfig'

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-systemtest#30]
When I try to run the jck tests, I can run test.jck8b fine, but test.jck8b.noconfig  stops almost immediately with this message:

make: Nothing to be done for 'test.jck8b.noconfig'.

**Comment by lumpfish** [comment]
The problem is that the JCK8B_TESTS macro is being used before it has been populated with all the test targets.  So after executing:
JCK8B_TESTS_NO_CONFIG:=$(filter-out $(JCK8B_TESTS_REQUIRING_CONFIG),$(JCK8B_TESTS))
JCK8B_TESTS_NO_CONFIG is empty rather than containing the test targets minus those which require the http and kerberos settings.

**Comment by adamfarley** [comment]
Looks good to me. Closing.
