### ISSUE TITLE
MathLoadTest+LockingLoadTest failing on HotSpot VMs (8 and 9) on x86

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-systemtest#8]
Issue as follows - need to determine correct behaviour and decide which VM is giving the correct result, and adjust test accordingly. Currently test is set up with the expected result from J9

```
MLT testStarted : testExp(net.adoptopenjdk.test.math.MathAPITest)
MLT testFailure: testExp(net.adoptopenjdk.test.math.MathAPITest): exp(double)[9] :: expected:<11.3842406513381> but was:<11.384240651338098>
MLT junit.framework.AssertionFailedError: exp(double)[9] :: expected:<11.3842406513381> but was:<11.384240651338098>
MLT     at junit.framework.Assert.fail(Assert.java:57)
```

Standalone test case that should show the problem:

```
import java.math.*;

public class Exp
{
 public static void main(String[] args)
 {
   String rc_String;
   rc_String = Double.toString(Math.exp(-1.2232D));
   if ( rc_String.equals("0.2942869403572507") ) {
     System.out.println ("Test 1 passed: Expected 0.2942869403572507, got " + rc_String);
   }
   else {
     System.out.println ("Test 1 failed: Expected 0.2942869403572507 (value returned by OpenJDK), got " + rc_String);
   }
 }
}
```

**Comment by Mesbah-Alam** [comment]
Fyi..This failure is seen in the ci.adopt builds too: 
1) https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_hs_systemtest_x86-64_linux/6/
2) https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_hs_systemtest_x86-64_linux/4/

**Comment by Mesbah-Alam** [comment]
Following discussion in https://github.com/eclipse/openj9/issues/1001#issuecomment-362041853 , there was a decision made that we accept both IBM and Oracle values for the failing junit test of exp() API, since this is a systemtest and the failure is after all a unit/functional test failure which we may ignore in context of a load test. 

The other alternative would be to use a propitiatory C program that  Robert Enenkel has in order to, quoting Robert,  "generate a list of test arguments, and a corresponding list of allowable pairs of functions values (f1,f2) such that our value is good if f1 <= x <= f2.  Generating this list would require a high accuracy reference function, but it would not have to be available to the open source program doing the test".

- This seems to be an overkill as far as this load test is concerned-- where the main objective is to run the tests parallelly.

**Comment by Mesbah-Alam** [comment]
@lumpfish , I asked for review from you for the PR related to this issue https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/71.

**Comment by Mesbah-Alam** [comment]
This issue can now be closed as the tests have been updated to accept the values which was causing the failure (ref: https://github.com/eclipse/openj9/issues/1001#issuecomment-362041853)
